const specifications = {
    "select": {
        "inputs": {
            "input": {"default": 0},
            "select": {},
            "selectat": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "math": {
        "inputs": {
            "input": {"default": 0},
            "input1": {"default": 0},
            "input2": {"default": 0},
            "amount": {}
        },
        "outputs": {
            "average": {},
            "ceil": {},
            "cosine": {},
            "difference": {},
            "floor": {},
            "logarithm": {},
            "maximum": {},
            "minimum": {},
            "modulo": {},
            "negation": {},
            "power": {},
            "product": {},
            "quotient": {},
            "reciprocal": {},
            "root": {},
            "round": {},
            "sine": {},
            "square": {},
            "sum": {},
            "absolute": {},
            "greater": {},
            "less": {}
        }
    },
    "logic": {
        "inputs": {
            "countvalue": {"default": 0.1},
            "highvalue": {"default": 1.0},
            "input": {},
            "input1": {},
            "input2": {},
            "input3": {},
            "input4": {},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {},
            "lowvalue": {"default": 0.0},
            "threshold": {"default": 1.0}
        },
        "outputs": {
            "and": {},
            "count": {},
            "countlow": {},
            "nand": {},
            "negated": {},
            "nor": {},
            "or": {},
            "xor": {}
        }
    },
    "copy": {
        "inputs": {
            "input": {"default": 0},
            "multiply": {"default": 1.0},
            "offset": {"default": 0.0}
        },
        "outputs": {
            "output": {}
        }
    },
    "clocktool": {
        "inputs": {
            "clock": {},
            "delay": {"default": 0},
            "divide": {"default": 1},
            "dutycycle": {},
            "gatelength": {},
            "multiply": {"default": 1},
            "reset": {},
            "inputpitch": {},
            "shift": {"default": 0}
        },
        "outputs": {
            "output": {},
            "outputpitch": {},
            "clockout": {}
        }
    },
    "bernoulli": {
        "inputs": {
            "distribution": {"default": 0.5},
            "input": {"default": 0},
            "probability1": {"default": 0.5},
            "probability2": {"default": 0.5},
            "probability3": {"default": 0.5},
            "probability4": {"default": 0.5}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {}
        }
    },
    "encoder": {
        "inputs": {
            "autozoom": {},
            "clear": {},
            "clearall": {},
            "color": {},
            "discrete": {},
            "dontsave": {"default": 0},
            "encoder": {"default": 1},
            "led": {},
            "ledfill": {},
            "loadpreset": {},
            "mode": {},
            "movementticks": {},
            "negativecolor": {},
            "notch": {},
            "outputoffset": {"default": 0},
            "outputscale": {"default": 2},
            "override": {},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "sensivity": {},
            "sharewithnext": {},
            "smooth": {},
            "snapforce": {},
            "snapto": {},
            "startvalue": {},
            "minvalue": {"default": -1.0},
            "maxvalue": {"default": 1.0},
            "wrap": {"default": 0},
            "speed": {"default": 1.0},
            "release": {"default": 0.0},
            "ledmode": {"default": 0},
            "ledcolor": {"default": 7}
        },
        "outputs": {
            "button": {},
            "moveddown": {},
            "movedup": {},
            "output": {},
            "valuechanged": {},
            "led": {}
        }
    },
    "switch": {
        "inputs": {
            "backward": {},
            "forward": {},
            "input1": {"default": 0},
            "input2": {"default": 0},
            "input3": {"default": 0},
            "input4": {"default": 0},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {},
            "input9": {},
            "input10": {},
            "input11": {},
            "input12": {},
            "input13": {},
            "input14": {},
            "input15": {},
            "input16": {},
            "offset": {"default": 0},
            "reset": {}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {},
            "output9": {},
            "output10": {},
            "output11": {},
            "output12": {},
            "output13": {},
            "output14": {},
            "output15": {},
            "output16": {}
        }
    },
    "mixer": {
        "inputs": {
            "input1": {"default": 0},
            "input2": {"default": 0},
            "input3": {},
            "input4": {},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {}
        },
        "outputs": {
            "average": {},
            "maximum": {},
            "minimum": {},
            "output": {}
        }
    },
    "random": {
        "inputs": {
            "clock": {},
            "maximum": {"default": 1},
            "minimum": {"default": 0},
            "steps": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "cvlooper": {
        "inputs": {
            "bypass": {},
            "clock": {},
            "cvin": {"default": 0},
            "gatein": {"default": 1},
            "length": {"default": 16},
            "offset": {"default": 0},
            "speed": {"default": 1},
            "record": {},
            "play": {},
            "stop": {},
            "loopswitch": {},
            "overdub": {},
            "overlay": {},
            "pause": {"default": "off"},
            "tapespeed": {}
        },
        "outputs": {
            "output": {},
            "cvout": {},
            "gateout": {},
            "recordled": {},
            "playled": {},
            "stopled": {}
        }
    },
    "contour": {
        "inputs": {
            "abortattack": {},
            "attack": {"default": 0},
            "attackshape": {},
            "decay": {"default": 0.2},
            "decayshape": {},
            "gate": {},
            "hold": {"default": 0},
            "level": {"default": 1.0},
            "loop": {"default": 0},
            "pitch": {},
            "predelay": {"default": 0.0},
            "release": {"default": 0.2},
            "releaseshape": {},
            "retrigger": {},
            "shape": {},
            "startfromzero": {},
            "sustain": {"default": 0.5},
            "swell": {},
            "swelllevel": {},
            "swellshape": {},
            "swelltime": {},
            "taptempo": {},
            "trigger": {},
            "velocity": {},
            "zerocrossing": {}
        },
        "outputs": {
            "endofattack": {},
            "endofdecay": {},
            "endofhold": {},
            "endofpredelay": {},
            "endofrelease": {},
            "inverted": {},
            "negated": {},
            "output": {}
        }
    },
    "lfo": {
        "inputs": {
            "bipolar": {"default": 0},
            "hz": {"default": 1},
            "level": {"default": 1},
            "offset": {"default": 0},
            "phase": {},
            "pulsewidth": {},
            "randomize": {},
            "rate": {},
            "skew": {},
            "sync": {},
            "syncphase": {},
            "taptempo": {},
            "waveform": {},
            "reset": {}
        },
        "outputs": {
            "cosine": {},
            "output": {},
            "paraboloid": {},
            "ramp": {},
            "sawtooth": {},
            "sine": {},
            "square": {},
            "triangle": {},
            "random": {}
        }
    },
    "spring": {
        "inputs": {
            "flowresistance": {"default": 0},
            "friction": {"default": 0},
            "gravity": {},
            "mass": {"default": 1},
            "reset": {},
            "shove": {},
            "shoveforce": {},
            "speed": {},
            "springforce": {"default": 1},
            "startposition": {},
            "startvelocity": {}
        },
        "outputs": {
            "position": {},
            "velocity": {}
        }
    },
    "transient": {
        "inputs": {
            "clock": {},
            "duration": {"default": 1},
            "end": {"default": 1},
            "freeze": {},
            "loop": {"default": 0},
            "pingpong": {},
            "reset": {},
            "start": {"default": 0}
        },
        "outputs": {
            "endoftransient": {},
            "output": {},
            "phase": {}
        }
    },
    "algoquencer": {
        "inputs": {
            "accentbutton": {},
            "accenthigh": {},
            "accentlow": {},
            "activity": {},
            "alternatebars": {},
            "alternatebutton": {},
            "alternaterepeats": {},
            "branches": {},
            "button1": {},
            "button2": {},
            "button3": {},
            "button4": {},
            "button5": {},
            "button6": {},
            "button7": {},
            "button8": {},
            "button9": {},
            "button10": {},
            "button11": {},
            "button12": {},
            "button13": {},
            "button14": {},
            "button15": {},
            "button16": {},
            "clear": {},
            "clearall": {},
            "clearpage": {},
            "clock": {},
            "dejavu": {"default": 1},
            "distribution": {},
            "dontsave": {},
            "fillorder": {},
            "fills": {},
            "gatelength": {},
            "length": {},
            "lengthbutton": {},
            "loadpreset": {},
            "morphs": {"default": 0},
            "mutebutton": {},
            "nextpattern": {},
            "offbeats": {},
            "pattern": {},
            "pitchhigh": {},
            "pitchlow": {},
            "pitchresolution": {},
            "pitch1": {},
            "pitch2": {},
            "pitch3": {},
            "pitch4": {},
            "pitch5": {},
            "pitch6": {},
            "pitch7": {},
            "pitch8": {},
            "pitch9": {},
            "pitch10": {},
            "pitch11": {},
            "pitch12": {},
            "pitch13": {},
            "pitch14": {},
            "pitch15": {},
            "pitch16": {},
            "preset": {},
            "prevpattern": {},
            "repeats": {},
            "reroll": {},
            "reset": {},
            "rollcount": {},
            "rolls": {},
            "rollstartvelo": {},
            "rollsteps": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "unmutebutton": {},
            "variation": {"default": 0},
            "transpose": {"default": 0},
            "steps": {},
            "root": {"default": 0},
            "degree": {"default": 0},
            "octave": {},
            "rhythm": {},
            "rhythmvariation": {}
        },
        "outputs": {
            "accent": {},
            "barled1": {},
            "barled2": {},
            "barled3": {},
            "barled4": {},
            "branch": {},
            "fillsled": {},
            "gate": {},
            "led1": {},
            "led2": {},
            "led3": {},
            "led4": {},
            "led5": {},
            "led6": {},
            "led7": {},
            "led8": {},
            "led9": {},
            "led10": {},
            "led11": {},
            "led12": {},
            "led13": {},
            "led14": {},
            "led15": {},
            "led16": {},
            "lengthoutput": {},
            "morphled": {},
            "muteled": {},
            "pitch": {},
            "rollvelocity": {},
            "startofbar": {},
            "trigger": {},
            "unmuteled": {}
        }
    },
    "arpeggio": {
        "inputs": {
            "autoreset": {},
            "butterfly": {"default": 0},
            "clock": {},
            "degree": {"default": 0},
            "direction": {"default": 0},
            "drop": {"default": 0},
            "harmonicshift": {},
            "noteshift": {},
            "octaves": {"default": 0},
            "pattern": {"default": 0},
            "pingpong": {"default": 0},
            "pitch": {"default": 0},
            "range": {"default": 0.2},
            "reset": {},
            "root": {"default": 0},
            "selectfill1": {},
            "selectfill2": {},
            "selectfill3": {},
            "selectfill4": {},
            "selectfill5": {},
            "selectnoteshift": {},
            "select1": {},
            "select3": {},
            "select5": {},
            "select7": {},
            "select9": {},
            "select11": {},
            "select13": {},
            "startnote": {},
            "transpose": {"default": 0},
            "tuningmode": {},
            "tuningpitch": {},
            "note1": {"default": 0},
            "note2": {"default": 0},
            "note3": {"default": 0},
            "note4": {"default": 0},
            "note5": {"default": 0},
            "note6": {"default": 0},
            "note7": {"default": 0},
            "note8": {"default": 0},
            "length": {"default": 1},
            "gate": {"default": 0.8}
        },
        "outputs": {
            "output": {},
            "pitch": {},
            "gate": {}
        }
    },
    "encoquencer": {
        "inputs": {
            "accumulatorrange": {},
            "autoreset": {},
            "buttoncolor": {},
            "buttonmode": {"default": 0},
            "clear": {},
            "clearall": {},
            "clearrepeats": {},
            "clearskips": {},
            "clearstartend": {},
            "clock": {},
            "composemode": {},
            "constantlength": {},
            "copy": {},
            "cvbase": {"default": 0},
            "cvnotches": {},
            "cvrange": {"default": 0.2},
            "defaultcv": {},
            "defaultgate": {},
            "degree": {"default": 0},
            "direction": {},
            "dontsave": {"default": 0},
            "endstep": {},
            "fadermode": {},
            "firstfader": {},
            "form": {},
            "gatelength": {},
            "harmonicshift": {},
            "holdcv": {},
            "invert": {},
            "keyboardcv": {},
            "keyboardgate": {},
            "keyboardmode": {},
            "ledpreview": {},
            "linktonext": {},
            "loadpreset": {},
            "luckyamount": {},
            "luckybuttons": {},
            "luckychance": {},
            "luckycvbase": {},
            "luckycvdrift": {},
            "luckycvs": {},
            "luckyfaders": {},
            "luckygatepattern": {},
            "luckygateprob": {},
            "luckygates": {},
            "luckyinvert": {},
            "luckyrandomizecv": {},
            "luckyratchets": {},
            "luckyrepeats": {},
            "luckyreverse": {},
            "luckyscope": {},
            "luckyshuffle": {},
            "luckyskips": {},
            "luckyspread": {},
            "luckyties": {},
            "metricsaver": {},
            "mute": {},
            "noteshift": {},
            "nume4s": {},
            "numfaders": {},
            "numsteps": {},
            "page": {},
            "paste": {},
            "pastebuttons": {},
            "pastefaders": {},
            "pattern": {},
            "pingpong": {"default": 0},
            "preset": {},
            "quantize": {"default": 2},
            "ratchetshift": {},
            "recordmode": {},
            "recordsilence": {},
            "repeatshift": {},
            "reset": {},
            "root": {"default": 0},
            "run": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "selectfill1": {},
            "selectfill2": {},
            "selectfill3": {},
            "selectfill4": {},
            "selectfill5": {},
            "selectnoteshift": {},
            "select1": {},
            "select3": {},
            "select5": {},
            "select7": {},
            "select9": {},
            "select11": {},
            "select13": {},
            "shiftsteps": {},
            "startstep": {},
            "taptempo": {},
            "transpose": {"default": 0},
            "tuningmode": {},
            "tuningpitch": {},
            "zorder": {},
            "length": {"default": 16},
            "steps": {"default": 16},
            "octave": {"default": 0},
            "swing": {"default": 0.0},
            "slide": {},
            "accent": {"default": 1.0},
            "velocity": {"default": 0.8},
            "variation": {"default": 0},
            "fillmode": {},
            "filllength": {},
            "fillrepeats": {}
        },
        "outputs": {
            "accumulator": {},
            "currentpage": {},
            "currentstep": {},
            "cv": {},
            "endstepout": {},
            "gate": {},
            "startofpart": {},
            "startofsequence": {},
            "startstepout": {}
        }
    },
    "euklid": {
        "inputs": {
            "beats": {"default": 5},
            "clock": {},
            "length": {"default": 16},
            "offset": {"default": 0},
            "reset": {},
            "rotate": {"default": 0},
            "steps": {"default": 8}
        },
        "outputs": {
            "output": {},
            "offbeats": {},
            "outputsignal": {}
        }
    },
    "motoquencer": {
        "inputs": {
            "accumulatorrange": {},
            "autoreset": {},
            "buttoncolor": {},
            "buttonmode": {"default": 0},
            "clear": {},
            "clearall": {},
            "clearrepeats": {},
            "clearskips": {},
            "clearstartend": {},
            "clock": {},
            "composemode": {},
            "constantlength": {},
            "copy": {},
            "cvbase": {"default": 0},
            "cvnotches": {},
            "cvrange": {"default": 0.2},
            "defaultcv": {},
            "defaultgate": {},
            "degree": {"default": 0},
            "direction": {},
            "dontsave": {},
            "endstep": {},
            "fadermode": {},
            "firstfader": {},
            "form": {},
            "gatelength": {},
            "harmonicshift": {},
            "holdcv": {},
            "invert": {},
            "keyboardcv": {},
            "keyboardgate": {},
            "keyboardmode": {},
            "linktonext": {},
            "loadpreset": {},
            "luckyamount": {},
            "luckybuttons": {},
            "luckychance": {},
            "luckycvbase": {},
            "luckycvdrift": {},
            "luckycvs": {},
            "luckyfaders": {},
            "luckygatepattern": {},
            "luckygateprob": {},
            "luckygates": {},
            "luckyinvert": {},
            "luckyrandomizecv": {},
            "luckyratchets": {},
            "luckyrepeats": {},
            "luckyreverse": {},
            "luckyscope": {},
            "luckyshuffle": {},
            "luckyskips": {},
            "luckyspread": {},
            "luckyties": {},
            "metricsaver": {},
            "mute": {},
            "noteshift": {},
            "numfaders": {},
            "numsteps": {},
            "page": {},
            "paste": {},
            "pastebuttons": {},
            "pastefaders": {},
            "pattern": {},
            "pingpong": {"default": 0},
            "preset": {},
            "quantize": {"default": 2},
            "ratchetshift": {},
            "recordmode": {},
            "recordsilence": {},
            "repeatshift": {},
            "reset": {},
            "root": {"default": 0},
            "run": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "selectfill1": {},
            "selectfill2": {},
            "selectfill3": {},
            "selectfill4": {},
            "selectfill5": {},
            "selectnoteshift": {},
            "select1": {},
            "select3": {},
            "select5": {},
            "select7": {},
            "select9": {},
            "select11": {},
            "select13": {},
            "shiftsteps": {},
            "startstep": {},
            "taptempo": {},
            "transpose": {"default": 0},
            "tuningmode": {},
            "tuningpitch": {},
            "length": {"default": 16},
            "steps": {"default": 16},
            "octave": {"default": 0},
            "swing": {"default": 0.0},
            "slide": {}
        },
        "outputs": {
            "accumulator": {},
            "currentpage": {},
            "currentstep": {},
            "cv": {},
            "endstepout": {},
            "gate": {},
            "startofpart": {},
            "startofsequence": {},
            "startstepout": {}
        }
    },
    "polytool": {
        "inputs": {
            "gateinput1": {},
            "gateinput2": {},
            "gateinput3": {},
            "gateinput4": {},
            "gateinput5": {},
            "gateinput6": {},
            "gateinput7": {},
            "gateinput8": {},
            "gateinput9": {},
            "gateinput10": {},
            "gateinput11": {},
            "gateinput12": {},
            "gateinput13": {},
            "gateinput14": {},
            "gateinput15": {},
            "gateinput16": {},
            "pitchinput1": {},
            "pitchinput2": {},
            "pitchinput3": {},
            "pitchinput4": {},
            "pitchinput5": {},
            "pitchinput6": {},
            "pitchinput7": {},
            "pitchinput8": {},
            "pitchinput9": {},
            "pitchinput10": {},
            "pitchinput11": {},
            "pitchinput12": {},
            "pitchinput13": {},
            "pitchinput14": {},
            "pitchinput15": {},
            "pitchinput16": {},
            "roundrobin": {"default": 0},
            "voiceallocation": {"default": 0}
        },
        "outputs": {
            "gateoutput1": {},
            "gateoutput2": {},
            "gateoutput3": {},
            "gateoutput4": {},
            "gateoutput5": {},
            "gateoutput6": {},
            "gateoutput7": {},
            "gateoutput8": {},
            "gateoutput9": {},
            "gateoutput10": {},
            "gateoutput11": {},
            "gateoutput12": {},
            "gateoutput13": {},
            "gateoutput14": {},
            "gateoutput15": {},
            "gateoutput16": {},
            "pitchoutput1": {},
            "pitchoutput2": {},
            "pitchoutput3": {},
            "pitchoutput4": {},
            "pitchoutput5": {},
            "pitchoutput6": {},
            "pitchoutput7": {},
            "pitchoutput8": {},
            "pitchoutput9": {},
            "pitchoutput10": {},
            "pitchoutput11": {},
            "pitchoutput12": {},
            "pitchoutput13": {},
            "pitchoutput14": {},
            "pitchoutput15": {},
            "pitchoutput16": {}
        }
    },
    "sequencer": {
        "inputs": {
            "cv1": {"default": 0},
            "cv2": {"default": 0},
            "cv3": {"default": 0},
            "cv4": {"default": 0},
            "cv5": {"default": 0},
            "cv6": {"default": 0},
            "cv7": {"default": 0},
            "cv8": {"default": 0},
            "gate1": {"default": 1},
            "gate2": {"default": 1},
            "gate3": {"default": 1},
            "gate4": {"default": 1},
            "gate5": {"default": 1},
            "gate6": {"default": 1},
            "gate7": {"default": 1},
            "gate8": {"default": 1},
            "pitch1": {"default": 0},
            "pitch2": {"default": 0},
            "pitch3": {"default": 0},
            "pitch4": {"default": 0},
            "pitch5": {"default": 0},
            "pitch6": {"default": 0},
            "pitch7": {"default": 0},
            "pitch8": {"default": 0},
            "steps": {"default": 0}
        },
        "outputs": {}
    },
    "case": {
        "inputs": {
            "case1": {},
            "case2": {},
            "case3": {},
            "case4": {},
            "case5": {},
            "case6": {},
            "case7": {},
            "case8": {},
            "case9": {},
            "case10": {},
            "case11": {},
            "case12": {},
            "case13": {},
            "case14": {},
            "case15": {},
            "case16": {},
            "else": {"default": 0},
            "value1": {},
            "value2": {},
            "value3": {},
            "value4": {},
            "value5": {},
            "value6": {},
            "value7": {},
            "value8": {},
            "value9": {},
            "value10": {},
            "value11": {},
            "value12": {},
            "value13": {},
            "value14": {},
            "value15": {},
            "value16": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "crossfader": {
        "inputs": {
            "fade": {"default": 0.5},
            "input1": {"default": 0},
            "input2": {"default": 0},
            "input3": {},
            "input4": {},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {},
            "position": {"default": 0.0}
        },
        "outputs": {
            "output": {}
        }
    },
    "delay": {
        "inputs": {
            "bypass": {},
            "clock": {},
            "cvin": {"default": 0},
            "delay": {"default": 1.0},
            "filenumber": {"default": 1},
            "gatein1": {},
            "gatein2": {},
            "gatein3": {},
            "gatein4": {},
            "gatein5": {},
            "gatein6": {},
            "gatein7": {},
            "gatein8": {},
            "load": {},
            "numberin": {},
            "sample": {},
            "save": {},
            "timewindow": {},
            "record": {},
            "play": {},
            "stop": {}
        },
        "outputs": {
            "cvout": {},
            "gateout1": {},
            "gateout2": {},
            "gateout3": {},
            "gateout4": {},
            "gateout5": {},
            "gateout6": {},
            "gateout7": {},
            "gateout8": {},
            "numberout": {},
            "overflow": {},
            "recordled": {},
            "playled": {},
            "stopled": {}
        }
    },
    "matrixmixer": {
        "inputs": {
            "auxin1": {},
            "auxin2": {},
            "auxin3": {},
            "auxin4": {},
            "button11": {},
            "button12": {},
            "button13": {},
            "button14": {},
            "button21": {},
            "button22": {},
            "button23": {},
            "button24": {},
            "button31": {},
            "button32": {},
            "button33": {},
            "button34": {},
            "button41": {},
            "button42": {},
            "button43": {},
            "button44": {},
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "input1": {"default": 0},
            "input2": {"default": 0},
            "input3": {"default": 0},
            "input4": {"default": 0},
            "loadpreset": {},
            "mixmax": {},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startvalue": {}
        },
        "outputs": {
            "led11": {},
            "led12": {},
            "led13": {},
            "led14": {},
            "led21": {},
            "led22": {},
            "led23": {},
            "led24": {},
            "led31": {},
            "led32": {},
            "led33": {},
            "led34": {},
            "led41": {},
            "led42": {},
            "led43": {},
            "led44": {},
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {}
        }
    },
    "quantizer": {
        "inputs": {
            "bypass": {"default": 0},
            "direction": {},
            "input": {"default": 0},
            "steps": {"default": 12},
            "trigger": {}
        },
        "outputs": {
            "changed": {},
            "output": {}
        }
    },
    "queue": {
        "inputs": {
            "clock": {},
            "input": {"default": 0}
        },
        "outputs": {
            "outputpos1": {},
            "outputpos2": {},
            "outputpos3": {},
            "outputpos4": {},
            "outputpos5": {},
            "outputpos6": {},
            "outputpos7": {},
            "outputpos8": {},
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {}
        }
    },
    "recorder": {
        "inputs": {
            "bypass": {},
            "clock": {},
            "cvin": {"default": 0},
            "filenumber": {},
            "gatein1": {},
            "gatein2": {},
            "gatein3": {},
            "gatein4": {},
            "gatein5": {},
            "gatein6": {},
            "gatein7": {},
            "gatein8": {},
            "load": {},
            "loop": {},
            "mode": {},
            "numberin": {},
            "pause": {},
            "playbackspeed": {},
            "playbutton": {},
            "recordbutton": {},
            "sample": {},
            "save": {},
            "scrub": {},
            "scrubposition": {},
            "select": {},
            "selectat": {},
            "stopbutton": {},
            "timewindow": {},
            "trimend": {},
            "trimstart": {}
        },
        "outputs": {
            "cvout": {},
            "gateout1": {},
            "gateout2": {},
            "gateout3": {},
            "gateout4": {},
            "gateout5": {},
            "gateout6": {},
            "gateout7": {},
            "gateout8": {},
            "numberout": {},
            "overflow": {},
            "playled": {},
            "recordled": {},
            "stopled": {}
        }
    },
    "sample": {
        "inputs": {
            "bypass": {},
            "gate": {},
            "input": {"default": 0},
            "sample": {},
            "timewindow": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "slew": {
        "inputs": {
            "gate": {},
            "input": {},
            "slew": {"default": 1},
            "slewdown": {},
            "slewup": {},
            "exponential": {},
            "linear": {},
            "scurve": {}
        },
        "outputs": {}
    },
    "button": {
        "inputs": {
            "button": {},
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "doubleclickmode": {},
            "loadpreset": {},
            "longpresstime": {},
            "offvalue": {"default": 0},
            "onvalue": {"default": 1},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startvalue": {"default": 0},
            "states": {},
            "value1": {},
            "value2": {},
            "value3": {},
            "value4": {},
            "momentary": {"default": 0},
            "triggeron": {},
            "triggeroff": {}
        },
        "outputs": {
            "inverted": {},
            "led": {},
            "longpress": {},
            "negated": {},
            "output": {},
            "shortpress": {}
        }
    },
    "buttongroup": {
        "inputs": {
            "button1": {},
            "button2": {},
            "button3": {},
            "button4": {},
            "button5": {},
            "button6": {},
            "button7": {},
            "button8": {},
            "button9": {},
            "button10": {},
            "button11": {},
            "button12": {},
            "button13": {},
            "button14": {},
            "button15": {},
            "button16": {},
            "button17": {},
            "button18": {},
            "button19": {},
            "button20": {},
            "button21": {},
            "button22": {},
            "button23": {},
            "button24": {},
            "button25": {},
            "button26": {},
            "button27": {},
            "button28": {},
            "button29": {},
            "button30": {},
            "button31": {},
            "button32": {},
            "clear": {},
            "clearall": {},
            "dontsave": {"default": 0},
            "loadpreset": {},
            "longpresstime": {},
            "maxactive": {"default": 1},
            "minactive": {"default": 1},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startbutton": {},
            "value1": {},
            "value2": {},
            "value3": {},
            "value4": {},
            "value5": {},
            "value6": {},
            "value7": {},
            "value8": {},
            "value9": {},
            "value10": {},
            "value11": {},
            "value12": {},
            "value13": {},
            "value14": {},
            "value15": {},
            "value16": {},
            "value17": {},
            "value18": {},
            "value19": {},
            "value20": {},
            "value21": {},
            "value22": {},
            "value23": {},
            "value24": {},
            "value25": {},
            "value26": {},
            "value27": {},
            "value28": {},
            "value29": {},
            "value30": {},
            "value31": {},
            "value32": {}
        },
        "outputs": {
            "buttonoutput1": {},
            "buttonoutput2": {},
            "buttonoutput3": {},
            "buttonoutput4": {},
            "buttonoutput5": {},
            "buttonoutput6": {},
            "buttonoutput7": {},
            "buttonoutput8": {},
            "buttonoutput9": {},
            "buttonoutput10": {},
            "buttonoutput11": {},
            "buttonoutput12": {},
            "buttonoutput13": {},
            "buttonoutput14": {},
            "buttonoutput15": {},
            "buttonoutput16": {},
            "buttonoutput17": {},
            "buttonoutput18": {},
            "buttonoutput19": {},
            "buttonoutput20": {},
            "buttonoutput21": {},
            "buttonoutput22": {},
            "buttonoutput23": {},
            "buttonoutput24": {},
            "buttonoutput25": {},
            "buttonoutput26": {},
            "buttonoutput27": {},
            "buttonoutput28": {},
            "buttonoutput29": {},
            "buttonoutput30": {},
            "buttonoutput31": {},
            "buttonoutput32": {},
            "buttonpress": {},
            "extrapress": {},
            "led1": {},
            "led2": {},
            "led3": {},
            "led4": {},
            "led5": {},
            "led6": {},
            "led7": {},
            "led8": {},
            "led9": {},
            "led10": {},
            "led11": {},
            "led12": {},
            "led13": {},
            "led14": {},
            "led15": {},
            "led16": {},
            "led17": {},
            "led18": {},
            "led19": {},
            "led20": {},
            "led21": {},
            "led22": {},
            "led23": {},
            "led24": {},
            "led25": {},
            "led26": {},
            "led27": {},
            "led28": {},
            "led29": {},
            "led30": {},
            "led31": {},
            "led32": {},
            "longpress": {},
            "output": {},
            "selectionchanged": {}
        }
    },
    "encoderbank": {
        "inputs": {
            "autozoom": {},
            "clear": {},
            "clearall": {},
            "color": {},
            "discrete": {},
            "dontsave": {"default": 0},
            "firstencoder": {"default": 1},
            "ledfill": {},
            "loadpreset": {},
            "mode": {},
            "negativecolor": {},
            "notch": {},
            "outputoffset": {"default": 0},
            "outputscale": {"default": 2},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "sensivity": {},
            "smooth": {},
            "snapforce": {},
            "snapto": {},
            "startvalue": {},
            "ledmode": {"default": 0},
            "ledcolor": {"default": 7},
            "sharewithnext": {"default": 0}
        },
        "outputs": {
            "button1": {},
            "button2": {},
            "button3": {},
            "button4": {},
            "button5": {},
            "button6": {},
            "button7": {},
            "button8": {},
            "led1": {},
            "led2": {},
            "led3": {},
            "led4": {},
            "led5": {},
            "led6": {},
            "led7": {},
            "led8": {},
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {}
        }
    },
    "faderbank": {
        "inputs": {
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "firstfader": {"default": 1},
            "ledcolor": {"default": 7},
            "ledvalue1": {"default": 0},
            "ledvalue2": {"default": 0},
            "ledvalue3": {"default": 0},
            "ledvalue4": {"default": 0},
            "ledvalue5": {"default": 0},
            "ledvalue6": {"default": 0},
            "ledvalue7": {"default": 0},
            "ledvalue8": {"default": 0},
            "ledvalue9": {},
            "ledvalue10": {},
            "ledvalue11": {},
            "ledvalue12": {},
            "ledvalue13": {},
            "ledvalue14": {},
            "ledvalue15": {},
            "ledvalue16": {},
            "loadpreset": {},
            "notches": {"default": 0},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startvalue": {},
            "outputscale": {"default": 2},
            "outputoffset": {"default": 0}
        },
        "outputs": {
            "button1": {},
            "button2": {},
            "button3": {},
            "button4": {},
            "button5": {},
            "button6": {},
            "button7": {},
            "button8": {},
            "button9": {},
            "button10": {},
            "button11": {},
            "button12": {},
            "button13": {},
            "button14": {},
            "button15": {},
            "button16": {},
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {},
            "output9": {},
            "output10": {},
            "output11": {},
            "output12": {},
            "output13": {},
            "output14": {},
            "output15": {},
            "output16": {}
        }
    },
    "fadermatrix": {
        "inputs": {
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "firstfader": {"default": 1},
            "ledcolor1": {},
            "ledcolor2": {},
            "ledcolor3": {},
            "ledcolor4": {},
            "ledvalue11": {"default": 0},
            "ledvalue12": {"default": 0},
            "ledvalue13": {"default": 0},
            "ledvalue14": {"default": 0},
            "ledvalue21": {"default": 0},
            "ledvalue22": {"default": 0},
            "ledvalue23": {"default": 0},
            "ledvalue24": {"default": 0},
            "ledvalue31": {"default": 0},
            "ledvalue32": {"default": 0},
            "ledvalue33": {"default": 0},
            "ledvalue34": {"default": 0},
            "ledvalue41": {"default": 0},
            "ledvalue42": {"default": 0},
            "ledvalue43": {"default": 0},
            "ledvalue44": {"default": 0},
            "loadpreset": {},
            "notches1": {"default": 0},
            "notches2": {"default": 0},
            "notches3": {"default": 0},
            "notches4": {"default": 0},
            "preset": {},
            "rowcolumn": {"default": 0},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startvalue1": {},
            "startvalue2": {},
            "startvalue3": {},
            "startvalue4": {}
        },
        "outputs": {
            "button11": {},
            "button12": {},
            "button13": {},
            "button14": {},
            "button21": {},
            "button22": {},
            "button23": {},
            "button24": {},
            "button31": {},
            "button32": {},
            "button33": {},
            "button34": {},
            "button41": {},
            "button42": {},
            "button43": {},
            "button44": {},
            "output11": {},
            "output12": {},
            "output13": {},
            "output14": {},
            "output21": {},
            "output22": {},
            "output23": {},
            "output24": {},
            "output31": {},
            "output32": {},
            "output33": {},
            "output34": {},
            "output41": {},
            "output42": {},
            "output43": {},
            "output44": {}
        }
    },
    "motorfader": {
        "inputs": {
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "fader": {"default": 1},
            "ledcolor": {},
            "ledvalue": {},
            "loadpreset": {},
            "notches": {"default": 0},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "sharewithnext": {},
            "startvalue": {}
        },
        "outputs": {
            "button": {},
            "output": {}
        }
    },
    "notebuttons": {
        "inputs": {
            "button1": {},
            "button2": {},
            "button3": {},
            "button4": {},
            "button5": {},
            "button6": {},
            "button7": {},
            "button8": {},
            "button9": {},
            "button10": {},
            "button11": {},
            "button12": {},
            "clear": {},
            "clearall": {},
            "clock": {},
            "dontsave": {},
            "loadpreset": {},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startnote": {}
        },
        "outputs": {
            "gate": {},
            "led1": {},
            "led2": {},
            "led3": {},
            "led4": {},
            "led5": {},
            "led6": {},
            "led7": {},
            "led8": {},
            "led9": {},
            "led10": {},
            "led11": {},
            "led12": {},
            "output": {},
            "semitone": {}
        }
    },
    "nudge": {
        "inputs": {
            "amount": {"default": 0.1},
            "buttondown": {},
            "buttonup": {},
            "clear": {},
            "clearall": {},
            "dontsave": {},
            "loadpreset": {},
            "maximum": {},
            "minimum": {},
            "offset": {},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "startvalue": {},
            "wrap": {}
        },
        "outputs": {
            "leddown": {},
            "ledup": {},
            "output": {}
        }
    },
    "pot": {
        "inputs": {
            "clear": {},
            "clearall": {},
            "discrete": {},
            "dontsave": {},
            "ledgauge": {},
            "loadpreset": {},
            "notch": {"default": 0},
            "outputscale": {"default": 1},
            "pot": {"default": 0},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "slope": {},
            "startvalue": {}
        },
        "outputs": {
            "absbipolar": {},
            "bipolar": {},
            "lefthalf": {},
            "lefthalfinv": {},
            "onchange": {},
            "output": {},
            "righthalf": {},
            "righthalfinv": {}
        }
    },
    "unusedfaders": {
        "inputs": {
            "firstfader": {"default": 1},
            "numfaders": {"default": 1},
            "select": {},
            "selectat": {}
        },
        "outputs": {}
    },
    "burst": {
        "inputs": {
            "count": {"default": 1},
            "hz": {},
            "rate": {"default": 0},
            "reset": {},
            "skip": {},
            "taptempo": {},
            "trigger": {},
            "number": {"default": 3},
            "length": {"default": 0.1}
        },
        "outputs": {
            "output": {}
        }
    },
    "flipflop": {
        "inputs": {
            "clear": {},
            "load": {},
            "loadvalue": {"default": 1},
            "reset": {},
            "set": {},
            "startvalue": {"default": 0},
            "toggle": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "gatetool": {
        "inputs": {
            "gatelength": {},
            "gatestretch": {},
            "inputedge": {},
            "inputgate": {},
            "inputtrigger": {},
            "maxgatelength": {},
            "mingatelength": {},
            "taptempo": {},
            "input": {},
            "length": {"default": 0.5},
            "delay": {"default": 0.0},
            "oneshot": {"default": 0}
        },
        "outputs": {
            "outputedge": {},
            "outputgate": {},
            "outputtrigger": {},
            "output": {}
        }
    },
    "once": {
        "inputs": {
            "delay": {"default": 0.01},
            "onlycoldstart": {},
            "trigger": {}
        },
        "outputs": {}
    },
    "timing": {
        "inputs": {
            "clock": {},
            "reset": {},
            "timing1": {},
            "timing2": {},
            "timing3": {},
            "timing4": {},
            "timing5": {},
            "timing6": {},
            "timing7": {},
            "timing8": {}
        },
        "outputs": {
            "output": {}
        }
    },
    "triggerdelay": {
        "inputs": {
            "clock": {},
            "delay": {"default": 1},
            "gatelength": {},
            "input": {"default": 0},
            "mute": {},
            "repeats": {"default": 1}
        },
        "outputs": {
            "output": {},
            "overflow": {}
        }
    },
    "adc": {
        "inputs": {
            "input": {"default": 0},
            "maximum": {},
            "minimum": {},
            "bit1": {},
            "bit2": {},
            "bit3": {},
            "bit4": {},
            "bit5": {},
            "bit6": {},
            "bit7": {},
            "bit8": {},
            "bit9": {},
            "bit10": {},
            "bit11": {},
            "bit12": {}
        },
        "outputs": {
            "output": {},
            "bit1": {},
            "bit2": {},
            "bit3": {},
            "bit4": {},
            "bit5": {},
            "bit6": {},
            "bit7": {},
            "bit8": {},
            "bit9": {},
            "bit10": {},
            "bit11": {},
            "bit12": {}
        }
    },
    "compare": {
        "inputs": {
            "compare": {"default": 0},
            "else": {"default": 0},
            "ifequal": {},
            "ifgreater": {},
            "ifless": {},
            "input": {"default": 0},
            "precision": {"default": 0.0}
        },
        "outputs": {
            "ifequal": {},
            "ifless": {},
            "ifgreater": {},
            "output": {}
        }
    },
    "dac": {
        "inputs": {
            "bit1": {},
            "bit2": {},
            "bit3": {},
            "bit4": {},
            "bit5": {},
            "bit6": {},
            "bit7": {},
            "bit8": {},
            "bit9": {},
            "bit10": {},
            "bit11": {},
            "bit12": {},
            "maximum": {},
            "minimum": {},
            "range": {"default": 1}
        },
        "outputs": {
            "output": {}
        }
    },
    "explin": {
        "inputs": {
            "endvalue": {"default": 0.01},
            "input": {"default": 0},
            "mix": {},
            "startvalue": {"default": 1}
        },
        "outputs": {
            "output": {}
        }
    },
    "ifequal": {
        "inputs": {
            "else": {"default": 0},
            "ifequal": {"default": 1},
            "input1": {"default": 0},
            "input2": {"default": 1},
            "precision": {"default": 0.0}
        },
        "outputs": {
            "output": {}
        }
    },
    "multicompare": {
        "inputs": {
            "compare1": {},
            "compare2": {},
            "compare3": {},
            "compare4": {},
            "compare5": {},
            "compare6": {},
            "compare7": {},
            "compare8": {},
            "else": {"default": 0},
            "ifequal1": {},
            "ifequal2": {},
            "ifequal3": {},
            "ifequal4": {},
            "ifequal5": {},
            "ifequal6": {},
            "ifequal7": {},
            "ifequal8": {},
            "input": {"default": 0}
        },
        "outputs": {
            "output": {}
        }
    },
    "calibrator": {
        "inputs": {
            "clear": {},
            "clearall": {},
            "clearhere": {},
            "dontsave": {"default": 0},
            "input": {"default": 0},
            "loadpreset": {},
            "nudgeamount": {},
            "nudgedown": {},
            "nudgeup": {},
            "preset": {},
            "savepreset": {},
            "select": {},
            "selectat": {},
            "tunehightail": {},
            "tunelowtail": {},
            "tune1": {},
            "tune2": {},
            "tune3": {},
            "tune4": {},
            "tune5": {},
            "tune6": {},
            "tune7": {},
            "tune8": {},
            "tune9": {},
            "output": {"default": 1},
            "referencepoint": {"default": 0},
            "save": {}
        },
        "outputs": {
            "correction": {},
            "leddown": {"default": 0},
            "ledup": {"default": 0},
            "output": {}
        }
    },
    "chord": {
        "inputs": {
            "degree": {"default": 0},
            "harmonicshift": {},
            "inversion": {"default": 0},
            "noteshift": {},
            "pitch": {"default": 0},
            "root": {"default": 0},
            "selectfill1": {},
            "selectfill2": {},
            "selectfill3": {},
            "selectfill4": {},
            "selectfill5": {},
            "selectnoteshift": {},
            "select1": {},
            "select3": {},
            "select5": {},
            "select7": {},
            "select9": {},
            "select11": {},
            "select13": {},
            "spread": {"default": 0},
            "transpose": {},
            "trigger": {},
            "tuningmode": {},
            "tuningpitch": {},
            "voicing": {"default": 0}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {}
        }
    },
    "detune": {
        "inputs": {
            "detune": {"default": 0},
            "input1": {},
            "input2": {},
            "input3": {},
            "input4": {},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {},
            "tuningmode": {"default": 0},
            "tuningpitch": {"default": 0}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {}
        }
    },
    "fold": {
        "inputs": {
            "foldby": {"default": 0.1},
            "input": {"default": 0},
            "maximum": {"default": 1.0},
            "minimum": {"default": 0.0},
            "fold": {"default": 0}
        },
        "outputs": {
            "output": {}
        }
    },
    "minifonion": {
        "inputs": {
            "bypass": {},
            "degree": {"default": 0},
            "harmonicshift": {},
            "input": {"default": 0},
            "noteshift": {},
            "root": {"default": 0},
            "selectfill1": {},
            "selectfill2": {},
            "selectfill3": {},
            "selectfill4": {},
            "selectfill5": {},
            "selectnoteshift": {},
            "select1": {},
            "select3": {},
            "select5": {},
            "select7": {},
            "select9": {},
            "select11": {},
            "select13": {},
            "transpose": {"default": 0},
            "trigger": {},
            "tuningmode": {},
            "tuningpitch": {}
        },
        "outputs": {
            "notechange": {},
            "output": {}
        }
    },
    "octave": {
        "inputs": {
            "detune": {"default": 0},
            "fifths": {},
            "input": {"default": 0},
            "spread": {"default": 0}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {}
        }
    },
    "sinfonionlink": {
        "inputs": {
            "beat": {},
            "chaoticdetune": {},
            "clock": {},
            "degree": {},
            "harmonicshift": {},
            "linkstate": {},
            "reset": {},
            "root": {},
            "step": {},
            "transpose": {}
        },
        "outputs": {}
    },
    "superjust": {
        "inputs": {
            "bypass": {"default": 0},
            "input1": {},
            "input2": {},
            "input3": {},
            "input4": {},
            "input5": {},
            "input6": {},
            "input7": {},
            "input8": {},
            "transpose": {},
            "tuningmode": {"default": 0},
            "tuningpitch": {"default": 0}
        },
        "outputs": {
            "output1": {},
            "output2": {},
            "output3": {},
            "output4": {},
            "output5": {},
            "output6": {},
            "output7": {},
            "output8": {}
        }
    },
    "vcotuner": {
        "inputs": {
            "basepitch": {},
            "concertpitch": {},
            "precision": {},
            "select": {},
            "selectat": {},
            "smooth": {},
            "tuningnote": {}
        },
        "outputs": {
            "cents": {},
            "hz": {},
            "intune": {},
            "ledflat": {},
            "ledintune": {},
            "ledsharp": {},
            "pitch": {},
            "referencepitch": {},
            "tuning": {},
            "vcofound": {}
        }
    },
    "firefacecontrol": {
        "inputs": {
            "mainoutput": { "default": 1 },
            "outputlevel1": {},
            "outputlevel2": {},
            "outputlevel3": {},
            "outputlevel4": {},
            "outputlevel5": {},
            "outputlevel6": {},
            "outputlevel7": {},
            "outputlevel8": {},
            "outputlevel9": {},
            "outputlevel10": {},
            "outputlevel11": {},
            "outputlevel12": {},
            "outputlevel13": {},
            "outputlevel14": {},
            "outputlevel15": {},
            "outputlevel16": {},
            "outputmix1in1": {},
            "outputmix1in2": {},
            "outputmix1in3": {},
            "outputmix1in4": {},
            "outputmix1in5": {},
            "outputmix1in6": {},
            "outputmix1in7": {},
            "outputmix1in8": {},
            "outputmix1in9": {},
            "outputmix1in10": {},
            "outputmix1in11": {},
            "outputmix1in12": {},
            "outputmix1in13": {},
            "outputmix1in14": {},
            "outputmix1in15": {},
            "outputmix1in16": {},
            "outputmix2in1": {},
            "outputmix2in2": {},
            "outputmix2in3": {},
            "outputmix2in4": {},
            "outputmix2in5": {},
            "outputmix2in6": {},
            "outputmix2in7": {},
            "outputmix2in8": {},
            "outputmix2in9": {},
            "outputmix2in10": {},
            "outputmix2in11": {},
            "outputmix2in12": {},
            "outputmix2in13": {},
            "outputmix2in14": {},
            "outputmix2in15": {},
            "outputmix2in16": {},
            "outputmix3in1": {},
            "outputmix3in2": {},
            "outputmix3in3": {},
            "outputmix3in4": {},
            "outputmix3in5": {},
            "outputmix3in6": {},
            "outputmix3in7": {},
            "outputmix3in8": {},
            "outputmix3in9": {},
            "outputmix3in10": {},
            "outputmix3in11": {},
            "outputmix3in12": {},
            "outputmix3in13": {},
            "outputmix3in14": {},
            "outputmix3in15": {},
            "outputmix3in16": {},
            "outputmix4in1": {},
            "outputmix4in2": {},
            "outputmix4in3": {},
            "outputmix4in4": {},
            "outputmix4in5": {},
            "outputmix4in6": {},
            "outputmix4in7": {},
            "outputmix4in8": {},
            "outputmix4in9": {},
            "outputmix4in10": {},
            "outputmix4in11": {},
            "outputmix4in12": {},
            "outputmix4in13": {},
            "outputmix4in14": {},
            "outputmix4in15": {},
            "outputmix4in16": {},
            "outputmix5in1": {},
            "outputmix5in2": {},
            "outputmix5in3": {},
            "outputmix5in4": {},
            "outputmix5in5": {},
            "outputmix5in6": {},
            "outputmix5in7": {},
            "outputmix5in8": {},
            "outputmix5in9": {},
            "outputmix5in10": {},
            "outputmix5in11": {},
            "outputmix5in12": {},
            "outputmix5in13": {},
            "outputmix5in14": {},
            "outputmix5in15": {},
            "outputmix5in16": {},
            "outputmix6in1": {},
            "outputmix6in2": {},
            "outputmix6in3": {},
            "outputmix6in4": {},
            "outputmix6in5": {},
            "outputmix6in6": {},
            "outputmix6in7": {},
            "outputmix6in8": {},
            "outputmix6in9": {},
            "outputmix6in10": {},
            "outputmix6in11": {},
            "outputmix6in12": {},
            "outputmix6in13": {},
            "outputmix6in14": {},
            "outputmix6in15": {},
            "outputmix6in16": {},
            "outputmix7in1": {},
            "outputmix7in2": {},
            "outputmix7in3": {},
            "outputmix7in4": {},
            "outputmix7in5": {},
            "outputmix7in6": {},
            "outputmix7in7": {},
            "outputmix7in8": {},
            "outputmix7in9": {},
            "outputmix7in10": {},
            "outputmix7in11": {},
            "outputmix7in12": {},
            "outputmix7in13": {},
            "outputmix7in14": {},
            "outputmix7in15": {},
            "outputmix7in16": {},
            "outputmix8in1": {},
            "outputmix8in2": {},
            "outputmix8in3": {},
            "outputmix8in4": {},
            "outputmix8in5": {},
            "outputmix8in6": {},
            "outputmix8in7": {},
            "outputmix8in8": {},
            "outputmix8in9": {},
            "outputmix8in10": {},
            "outputmix8in11": {},
            "outputmix8in12": {},
            "outputmix8in13": {},
            "outputmix8in14": {},
            "outputmix8in15": {},
            "outputmix8in16": {},
            "outputmix9in1": {},
            "outputmix9in2": {},
            "outputmix9in3": {},
            "outputmix9in4": {},
            "outputmix9in5": {},
            "outputmix9in6": {},
            "outputmix9in7": {},
            "outputmix9in8": {},
            "outputmix9in9": {},
            "outputmix9in10": {},
            "outputmix9in11": {},
            "outputmix9in12": {},
            "outputmix9in13": {},
            "outputmix9in14": {},
            "outputmix9in15": {},
            "outputmix9in16": {},
            "outputmix10in1": {},
            "outputmix10in2": {},
            "outputmix10in3": {},
            "outputmix10in4": {},
            "outputmix10in5": {},
            "outputmix10in6": {},
            "outputmix10in7": {},
            "outputmix10in8": {},
            "outputmix10in9": {},
            "outputmix10in10": {},
            "outputmix10in11": {},
            "outputmix10in12": {},
            "outputmix10in13": {},
            "outputmix10in14": {},
            "outputmix10in15": {},
            "outputmix10in16": {},
            "outputmix11in1": {},
            "outputmix11in2": {},
            "outputmix11in3": {},
            "outputmix11in4": {},
            "outputmix11in5": {},
            "outputmix11in6": {},
            "outputmix11in7": {},
            "outputmix11in8": {},
            "outputmix11in9": {},
            "outputmix11in10": {},
            "outputmix11in11": {},
            "outputmix11in12": {},
            "outputmix11in13": {},
            "outputmix11in14": {},
            "outputmix11in15": {},
            "outputmix11in16": {},
            "outputmix12in1": {},
            "outputmix12in2": {},
            "outputmix12in3": {},
            "outputmix12in4": {},
            "outputmix12in5": {},
            "outputmix12in6": {},
            "outputmix12in7": {},
            "outputmix12in8": {},
            "outputmix12in9": {},
            "outputmix12in10": {},
            "outputmix12in11": {},
            "outputmix12in12": {},
            "outputmix12in13": {},
            "outputmix12in14": {},
            "outputmix12in15": {},
            "outputmix12in16": {},
            "outputmix13in1": {},
            "outputmix13in2": {},
            "outputmix13in3": {},
            "outputmix13in4": {},
            "outputmix13in5": {},
            "outputmix13in6": {},
            "outputmix13in7": {},
            "outputmix13in8": {},
            "outputmix13in9": {},
            "outputmix13in10": {},
            "outputmix13in11": {},
            "outputmix13in12": {},
            "outputmix13in13": {},
            "outputmix13in14": {},
            "outputmix13in15": {},
            "outputmix13in16": {},
            "outputmix14in1": {},
            "outputmix14in2": {},
            "outputmix14in3": {},
            "outputmix14in4": {},
            "outputmix14in5": {},
            "outputmix14in6": {},
            "outputmix14in7": {},
            "outputmix14in8": {},
            "outputmix14in9": {},
            "outputmix14in10": {},
            "outputmix14in11": {},
            "outputmix14in12": {},
            "outputmix14in13": {},
            "outputmix14in14": {},
            "outputmix14in15": {},
            "outputmix14in16": {},
            "outputmix15in1": {},
            "outputmix15in2": {},
            "outputmix15in3": {},
            "outputmix15in4": {},
            "outputmix15in5": {},
            "outputmix15in6": {},
            "outputmix15in7": {},
            "outputmix15in8": {},
            "outputmix15in9": {},
            "outputmix15in10": {},
            "outputmix15in11": {},
            "outputmix15in12": {},
            "outputmix15in13": {},
            "outputmix15in14": {},
            "outputmix15in15": {},
            "outputmix15in16": {},
            "outputmix16in1": {},
            "outputmix16in2": {},
            "outputmix16in3": {},
            "outputmix16in4": {},
            "outputmix16in5": {},
            "outputmix16in6": {},
            "outputmix16in7": {},
            "outputmix16in8": {},
            "outputmix16in9": {},
            "outputmix16in10": {},
            "outputmix16in11": {},
            "outputmix16in12": {},
            "outputmix16in13": {},
            "outputmix16in14": {},
            "outputmix16in15": {},
            "outputmix16in16": {},
            "pan1": {},
            "pan2": {},
            "pan3": {},
            "pan4": {},
            "pan5": {},
            "pan6": {},
            "pan7": {},
            "pan8": {},
            "pan9": {},
            "pan10": {},
            "pan11": {},
            "pan12": {},
            "pan13": {},
            "pan14": {},
            "pan15": {},
            "pan16": {},
            "phonesoutput1": {},
            "phonesoutput2": {},
            "postfader1": {},
            "postfader2": {},
            "postfader3": {},
            "postfader4": {},
            "postfader5": {},
            "postfader6": {},
            "postfader7": {},
            "postfader8": {},
            "postfader9": {},
            "postfader10": {},
            "postfader11": {},
            "postfader12": {},
            "postfader13": {},
            "postfader14": {},
            "postfader15": {},
            "postfader16": {},
            "select": {},
            "selectat": {},
            "trs": { "default": 1 },
            "unmute1": {},
            "unmute2": {},
            "unmute3": {},
            "unmute4": {},
            "unmute5": {},
            "unmute6": {},
            "unmute7": {},
            "unmute8": {},
            "unmute9": {},
            "unmute10": {},
            "unmute11": {},
            "unmute12": {},
            "unmute13": {},
            "unmute14": {},
            "unmute15": {},
            "unmute16": {},
            "update": {}
        },
        "outputs": {}
    },
    "midifileplayer": {
        "inputs": {
            "bendpitch": {},
            "ccnumber1": { "default": 0 },
            "ccnumber2": { "default": 0 },
            "ccnumber3": {},
            "ccnumber4": {},
            "channel": {},
            "clock": {},
            "end": {},
            "file": { "default": 1 },
            "highestnote": {},
            "holdvelocity": {},
            "loop": { "default": 0 },
            "lowestnote": {},
            "notegap": {},
            "note1": {},
            "note2": {},
            "note3": {},
            "note4": {},
            "note5": {},
            "note6": {},
            "note7": {},
            "note8": {},
            "note9": {},
            "note10": {},
            "note11": {},
            "note12": {},
            "note13": {},
            "note14": {},
            "note15": {},
            "note16": {},
            "pitchbendrange": {},
            "reset": {},
            "roundrobin": {},
            "speed": { "default": 1.0 },
            "track": {},
            "transpose": { "default": 0 },
            "tuningmode": {},
            "tuningpitch": {},
            "voiceallocation": { "default": 0 },
            "start": {},
            "stop": {},
            "pause": {},
            "continue": {},
            "filename": {}
        },
        "outputs": {
            "bank": {},
            "cctrigger1": {},
            "cctrigger2": {},
            "cctrigger3": {},
            "cctrigger4": {},
            "cc1": {},
            "cc2": {},
            "cc3": {},
            "cc4": {},
            "clockout": {},
            "endoftrack": {},
            "error": {},
            "gate1": {},
            "gate2": {},
            "gate3": {},
            "gate4": {},
            "gate5": {},
            "gate6": {},
            "gate7": {},
            "gate8": {},
            "midiclock": {},
            "modwheel": {},
            "notegate1": {},
            "notegate2": {},
            "notegate3": {},
            "notegate4": {},
            "notegate5": {},
            "notegate6": {},
            "notegate7": {},
            "notegate8": {},
            "notegate9": {},
            "notegate10": {},
            "notegate11": {},
            "notegate12": {},
            "notegate13": {},
            "notegate14": {},
            "notegate15": {},
            "notegate16": {},
            "pitchbend": {},
            "pitch1": {},
            "pitch2": {},
            "pitch3": {},
            "pitch4": {},
            "pitch5": {},
            "pitch6": {},
            "pitch7": {},
            "pitch8": {},
            "portamento": {},
            "pressure1": {},
            "pressure2": {},
            "pressure3": {},
            "pressure4": {},
            "pressure5": {},
            "pressure6": {},
            "pressure7": {},
            "pressure8": {},
            "program": {},
            "programchange": {},
            "soft": {},
            "trigger1": {},
            "trigger2": {},
            "trigger3": {},
            "trigger4": {},
            "trigger5": {},
            "trigger6": {},
            "trigger7": {},
            "trigger8": {},
            "velocity1": {},
            "velocity2": {},
            "velocity3": {},
            "velocity4": {},
            "velocity5": {},
            "velocity6": {},
            "velocity7": {},
            "velocity8": {},
            "volume": {}
        }
    },
    "midiin": {
        "inputs": {
            "bendpitch": {},
            "ccnumber1": { "default": 0 },
            "ccnumber2": { "default": 0 },
            "ccnumber3": {},
            "ccnumber4": {},
            "channel": {},
            "highestnote": {},
            "holdvelocity": {},
            "initialrunning": {},
            "lowestnote": {},
            "notegap": {},
            "note1": {},
            "note2": {},
            "note3": {},
            "note4": {},
            "note5": {},
            "note6": {},
            "note7": {},
            "note8": {},
            "note9": {},
            "note10": {},
            "note11": {},
            "note12": {},
            "note13": {},
            "note14": {},
            "note15": {},
            "note16": {},
            "pitchbendrange": {},
            "roundrobin": {},
            "systemreset": {},
            "transpose": {},
            "trs": {},
            "tuningmode": { "default": "off" },
            "tuningpitch": { "default": 2 },
            "usb": { "default": 0 },
            "voiceallocation": { "default": 0 }
        },
        "outputs": {
            "active": {},
            "bank": {},
            "cctrigger1": {},
            "cctrigger2": {},
            "cctrigger3": {},
            "cctrigger4": {},
            "cc1": {},
            "cc2": {},
            "cc3": {},
            "cc4": {},
            "clock": {},
            "clock4": {},
            "clock8": {},
            "clock8t": {},
            "clock16": {},
            "continue": {},
            "gate": {},
            "gate1": {},
            "gate2": {},
            "gate3": {},
            "gate4": {},
            "gate5": {},
            "gate6": {},
            "gate7": {},
            "gate8": {},
            "midiclock": {},
            "modwheel": {},
            "notegate1": {},
            "notegate2": {},
            "notegate3": {},
            "notegate4": {},
            "notegate5": {},
            "notegate6": {},
            "notegate7": {},
            "notegate8": {},
            "notegate9": {},
            "notegate10": {},
            "notegate11": {},
            "notegate12": {},
            "notegate13": {},
            "notegate14": {},
            "notegate15": {},
            "notegate16": {},
            "pitch": {},
            "pitchbend": {},
            "pitch1": {},
            "pitch2": {},
            "pitch3": {},
            "pitch4": {},
            "pitch5": {},
            "pitch6": {},
            "pitch7": {},
            "pitch8": {},
            "portamento": {},
            "pressure1": {},
            "pressure2": {},
            "pressure3": {},
            "pressure4": {},
            "pressure5": {},
            "pressure6": {},
            "pressure7": {},
            "pressure8": {},
            "program": {},
            "programchange": {},
            "running": {},
            "soft": {},
            "start": {},
            "stop": {},
            "trigger": {},
            "trigger1": {},
            "trigger2": {},
            "trigger3": {},
            "trigger4": {},
            "trigger5": {},
            "trigger6": {},
            "trigger7": {},
            "trigger8": {},
            "velocity1": {},
            "velocity2": {},
            "velocity3": {},
            "velocity4": {},
            "velocity5": {},
            "velocity6": {},
            "velocity7": {},
            "velocity8": {},
            "volume": {}
        }
    },
    "midiout": {
        "inputs": {
            "activesensing": {},
            "allnotesoff": {},
            "allsoundoff": {},
            "bank": {},
            "ccnumber1": { "default": 0 },
            "ccnumber2": { "default": 0 },
            "ccnumber3": {},
            "ccnumber4": {},
            "ccnumber5": {},
            "ccnumber6": {},
            "ccnumber7": {},
            "ccnumber8": {},
            "cctrigger1": {},
            "cctrigger2": {},
            "cctrigger3": {},
            "cctrigger4": {},
            "cctrigger5": {},
            "cctrigger6": {},
            "cctrigger7": {},
            "cctrigger8": {},
            "cc1": {},
            "cc2": {},
            "cc3": {},
            "cc4": {},
            "cc5": {},
            "cc6": {},
            "cc7": {},
            "cc8": {},
            "channel": {},
            "channelpressure": {},
            "clock": {},
            "damper": {},
            "delayinitialccs": {},
            "gate": { "default": 0 },
            "gate1": { "default": 0 },
            "gate2": {},
            "gate3": {},
            "gate4": {},
            "gate5": {},
            "gate6": {},
            "gate7": {},
            "gate8": {},
            "highestnote": {},
            "legato": {},
            "lowestnote": {},
            "midiclock": {},
            "modwheel": {},
            "notegatevelocity1": {},
            "notegatevelocity2": {},
            "notegatevelocity3": {},
            "notegatevelocity4": {},
            "notegatevelocity5": {},
            "notegatevelocity6": {},
            "notegatevelocity7": {},
            "notegatevelocity8": {},
            "notegatevelocity9": {},
            "notegatevelocity10": {},
            "notegatevelocity11": {},
            "notegatevelocity12": {},
            "notegatevelocity13": {},
            "notegatevelocity14": {},
            "notegatevelocity15": {},
            "notegatevelocity16": {},
            "notegate1": {},
            "notegate2": {},
            "notegate3": {},
            "notegate4": {},
            "notegate5": {},
            "notegate6": {},
            "notegate7": {},
            "notegate8": {},
            "notegate9": {},
            "notegate10": {},
            "notegate11": {},
            "notegate12": {},
            "notegate13": {},
            "notegate14": {},
            "notegate15": {},
            "notegate16": {},
            "noteoffvelocity1": {},
            "noteoffvelocity2": {},
            "noteoffvelocity3": {},
            "noteoffvelocity4": {},
            "noteoffvelocity5": {},
            "noteoffvelocity6": {},
            "noteoffvelocity7": {},
            "noteoffvelocity8": {},
            "note1": {},
            "note2": {},
            "note3": {},
            "note4": {},
            "note5": {},
            "note6": {},
            "note7": {},
            "note8": {},
            "note9": {},
            "note10": {},
            "note11": {},
            "note12": {},
            "note13": {},
            "note14": {},
            "note15": {},
            "note16": {},
            "pitchbend": {},
            "pitchbendrange": {},
            "pitchstabilization": {},
            "pitchtracking": {},
            "pitch": { "default": 0 },
            "pitch1": { "default": 0 },
            "pitch2": {},
            "pitch3": {},
            "pitch4": {},
            "pitch5": {},
            "pitch6": {},
            "pitch7": {},
            "pitch8": {},
            "portamento": {},
            "pressure1": {},
            "pressure2": {},
            "pressure3": {},
            "pressure4": {},
            "pressure5": {},
            "pressure6": {},
            "pressure7": {},
            "pressure8": {},
            "program": {},
            "programchange": { "default": 0 },
            "running": {},
            "select": {},
            "selectat": {},
            "soft": {},
            "sostenuto": {},
            "start": {},
            "stop": {},
            "systemreset": {},
            "triggerdelay": {},
            "trs": {},
            "updateccs": {},
            "updaterate": {},
            "usb": { "default": 0 },
            "velocity": { "default": 1.0 },
            "velocity1": { "default": 1 },
            "velocity2": {},
            "velocity3": {},
            "velocity4": {},
            "velocity5": {},
            "velocity6": {},
            "velocity7": {},
            "velocity8": {},
            "volume": {},
            "aftertouch": { "default": 0.0 },
            "polykeypressure": { "default": 0.0 },
            "ccvalue1": { "default": 0.0 },
            "ccvalue2": { "default": 0.0 },
            "ccvalue3": {},
            "ccvalue4": {},
            "reset": {},
            "sysex": {},
            "tousb": {}
        },
        "outputs": {}
    },
    "midithrough": {
        "inputs": {
            "fromtrs": {},
            "fromusb": {},
            "totrs": {},
            "tousb": {}
        },
        "outputs": {}
    },
    "droid": {
        "inputs": {
            "calibrate": {},
            "clear": {},
            "clearall": {},
            "ledbrightness": { "default": 1 },
            "lpfilter1": { "default": 0.25 },
            "lpfilter2": { "default": 0.25 },
            "lpfilter3": { "default": 0.25 },
            "lpfilter4": { "default": 0.25 },
            "lpfilter5": { "default": 0.25 },
            "lpfilter6": { "default": 0.25 },
            "lpfilter7": { "default": 0.25 },
            "lpfilter8": { "default": 0.25 },
            "maxslope1": { "default": 0.25 },
            "maxslope2": { "default": 0.25 },
            "maxslope3": { "default": 0.25 },
            "maxslope4": { "default": 0.25 },
            "maxslope5": { "default": 0.25 },
            "maxslope6": { "default": 0.25 },
            "maxslope7": { "default": 0.25 },
            "maxslope8": { "default": 0.25 },
            "m4faderspeed": {},
            "m4notchpower": {},
            "startcontrollerupgrade": {},
            "startx7upgrade": {},
            "statusdump": {},
            "uislowdown": {}
        },
        "outputs": {}
    },
    "outputcalibrator": {
        "inputs": {
            "cancel": {},
            "loaddefaults": {},
            "nudgedown": {},
            "nudgeup": {},
            "output": { "default": 1 },
            "referencepoint": { "default": 0 },
            "save": {}
        },
        "outputs": {
            "calibration": {},
            "dirty": {},
            "uncalibrated": {}
        }
    }
}
export default specifications;
